name: "Deploy PDF"
on:
  pull_request:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build devShell
      run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
    - name: Build the resume
      shell: 'nix develop -c bash -e {0}'
      run: rendercv render Francesco_Bozzo_CV.yaml
    - name: Publish the resume as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Francesco_Bozzo_CV.pdf
        path: rendercv_output/Francesco_Bozzo_CV.pdf
